scene.setBackgroundColor(13)
game.showLongText("Pythagorean Theorem Solver when you are given A & B: Enter two the measurements of two sides of your triangle ", DialogLayout.Center)
pause(1000)
game.showLongText("Enter side 1 (click A to continue)", DialogLayout.Center)
let Side_1 = game.askForNumber("")
game.showLongText("Enter side 2", DialogLayout.Center)
let Side_2 = game.askForNumber("")
let side_3 = game.askForNumber("")
